package com.example.submission_akhir_jetpackcompose.model

object MovieDataSource {
    val movieData = listOf(
        MovieDetail(1,
            "Avengers : Infinity War",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/Avengers%20Infinity%20War.jpg",
            40000,
            "XXI, CGV, Platinum Cineplex",
            "The Avengers must stop Thanos, an intergalactic warlord, from getting his hands on all the infinity stones. However, Thanos is prepared to go to any lengths to carry out his insane plan."

        ),
        MovieDetail(2,
            "Blackpanther : Wakanda Forever",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/Blackpanther%20-%20Wakanda%20Forever.jpeg",
            40000,
            "XXI, CGV",
            "Queen Ramonda, Shuri, M'Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T'Challa's death. As the Wakandans strive to embrace their next chapter, the heroes must band together with Nakia and Everett Ross to forge a new path for their beloved kingdom."
        ),
        MovieDetail(3,
            "Buya Hamka",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/Buya%20Hamka.jpg",
            40000,
            "XXI, CGV, Platinum Cineplex",
            "VOL. I: The period in which Hamka became the administrator of Muhammadiyah in Makassar and succeeded in making rapid progress to the organization. Hamka also started writing newspaper literature and his romance stories were liked by readers. Hamka and his family moved to Medan, because Hamka was appointed chief editor of the Community Guidelines magazine. This position made Hamka begin to clash with the Japanese and had to be closed down because he was considered dangerous. Hamka's family life was shaken when one of their children died of illness. Hamka's attempts to approach the Japanese were seen as sycophant and despised, so Hamka was asked to resign from his position as Muhammadiyah administrator."
        ),
        MovieDetail(4,
            "Guardian of the Galaxy Vol 3",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/Guardian%20of%20the%20Galaxy%20Vol%203.jpg",
            40000,
            "XXI, CGV",
            "Still reeling from the loss of Gamora, Peter Quill must rally his team to defend the universe and protect one of their own. If the mission is not completely successful, it could possibly lead to the end of the Guardians as we know them."
        ),
        MovieDetail(5,
            "Guy Ritchie's The Govenant",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/Guy%20Ritchie's%20The%20Govenant.jpg",
            40000,
            "XXI, CGV, Platinum Cineplex",
            "During the war in Afghanistan, a local interpreter risks his own life to carry an injured sergeant across miles of gruelling terrain."
        ),
        MovieDetail(6,
            "Ride On",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/Ride%20On.jpg",
            40000,
            "XXI, CGV",
            "Washed-up stuntman Luo can barely make ends meet, let alone take care of his beloved stunt horse, Red Hare. Luo reluctantly seeks help from his estranged daughter and her lawyer boyfriend when notified the horse may be auctioned off to pay his debts. Luo and Red Hare become an overnight media sensation when their fight with debt collectors goes viral."
        ),
        MovieDetail(7,
            "John Wick Chapter 4",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/John%20Wick%20-%20Chapter%204.jpg",
            40000,
            "XXI, CGV, Platinum Cineplex",
            "With the price on his head ever increasing, legendary hit man John Wick takes his fight against the High Table global as he seeks out the most powerful players in the underworld, from New York to Paris to Japan to Berlin."
        ),
        MovieDetail(8,
            "The Super Mario Bros. Movie",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/The%20Super%20Mario%20Bros.%20Movie.jpg",
            40000,
            "XXI, CGV",
            "With help from Princess Peach, Mario gets ready to square off against the all-powerful Bowser to stop his plans from conquering the world."
        ),
        MovieDetail(9,
            "Ant-Man and the Wasp : Quantumania",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/Ant-Man%20and%20the%20Wasp%20-%20Quantumania.jpg",
            40000,
            "XXI, CGV, Platinum Cineplex",
            "Ant-Man and the Wasp find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that pushes them beyond the limits of what they thought was possible."
        ),
        MovieDetail(10,
            "Avatar 2 : The Way of Water",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/Avatar%202%20-%20The%20Way%20of%20Water.jpg",
            40000,
            "XXI, CGV",
            "Jake Sully and Ney'tiri have formed a family and are doing everything to stay together. However, they must leave their home and explore the regions of Pandora. When an ancient threat resurfaces, Jake must fight a difficult war against the humans."
        ),
        MovieDetail(11,
            "Star Wars : The Rise of Skywalker",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/Star%20Wars%20-%20The%20Rise%20of%20Skywalker.jpg",
            40000,
            "XXI, CGV, Platinum Cineplex",
            "The revival of Emperor Palpatine resurrects the battle between the Resistance and the First Order while the Jedi's legendary conflict with the Sith Lord comes to a head."
        ),
        MovieDetail(12,
            "Top Gun : Maverick",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/Top%20Gun%20-%20Maverick.jpg",
            40000,
            "XXI, CGV,",
            "After more than 30 years of service as one of the Navy's top aviators, Pete \"Maverick\" Mitchell is where he belongs, pushing the envelope as a courageous test pilot and dodging the advancement in rank that would ground him. Training a detachment of graduates for a special assignment, Maverick must confront the ghosts of his past and his deepest fears, culminating in a mission that demands the ultimate sacrifice from those who choose to fly it."
        ),
        MovieDetail(13,
            "Headshot",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/Headshot.jpg",
            40000,
            "XXI, CGV, Platinum Cineplex",
            "A man suffering from amnesia washes ashore and a young doctor nurses him back to health. His past resurfaces to haunt them both in violent fashion."
        ),
        MovieDetail(14,
            "The Night Comes for Us",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/The%20Night%20Comes%20for%20Us.jpg",
            40000,
            "XXI, CGV",
            "Ito, a gangland enforcer, is stuck in the middle of a treacherous and violent insurrection within his Triad crime family."
        ),
        MovieDetail(15,
            "The Big 4",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/The%20Big%204.jpg",
            40000,
            "XXI, CGV, Platinum Cineplex",
            "Four retired assassins spring back into action when they cross paths with a straight-arrow cop who is determined to track down an elusive murderer that has something to do with their shared past."
        ),
        MovieDetail(16,
            "Plane",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/Plane.jpg",
            40000,
            "XXI, CGV",
            "Pilot Brodie Torrance saves passengers from a lightning strike by making a risky landing on a war-torn island -- only to find that surviving the landing was just the beginning. When dangerous rebels take most of the passengers hostage, the only person Torrance can count on for help is Louis Gaspare, an accused murderer who was being transported by the FBI."
        ),
        MovieDetail(17,
            "The Greatest Showman",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/The%20Greatest%20Showman.jpg",
            40000,
            "XXI, CGV, Platinum Cineplex",
            "P T Barnum becomes a worldwide sensation in the show business. His imagination and innovative ideas take him to the top of his game."
        ),
        MovieDetail(18,
            "Hit & Run",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/Hit%20%26%20Run.jpg",
            40000,
            "XXI, CGV",
            "A celebrity policeman who is followed by cameras everywhere because he has his own reality show. He is assigned to arrest a drug kingpin who has just escaped from prison. Unfortunately, this time he must be paired with a conman."
        ),
        MovieDetail(19,
            "Milea : Suara dari Dilan",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/Milea%20-%20Suara%20dari%20Dilan.jpg",
            40000,
            "XXI, CGV, Platinum Cineplex",
            "There is no more beautiful story than a love story in high school. It's the same as the love story of Dilan and Milea. From the initial hate to love each other. From the beginning it was sweet to become complicated. Approaching the grand reunion, Dilan decided to retell those times."
        ),
        MovieDetail(20,
            "Avengers Endgame",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/Avengers%20Endgame.jpg",
            40000,
            "XXI, CGV",
            "After Thanos, an intergalactic warlord, disintegrates half of the universe, the Avengers must reunite and assemble again to reinvigorate their trounced allies and restore balance."
        ),
        MovieDetail(21,
            "Dilan 1991",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/Dilan%201991.jpg",
            40000,
            "XXI, CGV, Platinum Cineplex",
            "The love story of Dilan and Milea will continue. In the Dilan 1991 film, their love story will begin to be tested. Dilan and Milea have to go through many obstacles, can their love survive?"
        ),
        MovieDetail(22,
            "Mission : Impossible - Fallout",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/Mission%20Impossible%20-%20Fallout.jpg",
            40000,
            "XXI, CGV",
            "A group of terrorists plans to detonate three plutonium cores for a simultaneous nuclear attack on different cities. Ethan Hunt, along with his IMF team, sets out to stop the carnage."
        ),
        MovieDetail(23,
            "Foxtrot Six",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/Foxtrot%20Six.jpg",
            40000,
            "XXI, CGV, Platinum Cineplex",
            "A group of elite soldiers embark on a violent and dangerous mission to save Indonesia from a hostile takeover."
        ),
        MovieDetail(24,
            "Doctor Strange in the Multiverse of Madness",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/Doctor%20Strange%20in%20the%20Multiverse%20of%20Madness.jpg",
            40000,
            "XXI, CGV",
            "Doctor Strange teams up with a mysterious teenage girl from his dreams who can travel across multiverses, to battle multiple threats, including other-universe versions of himself, which threaten to wipe out millions across the multiverse."
        ),
        MovieDetail(25,
            "Thor : Love and Thunder",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/Thor%20-%20Love%20and%20Thunder.jpeg",
            40000,
            "XXI, CGV, Platinum Cineplex",
            "Thor embarks on a journey unlike anything he's ever faced -- a quest for inner peace. However, his retirement gets interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods. To combat the threat, Thor enlists the help of King Valkyrie, Korg and ex-girlfriend Jane Foster, who -- to his surprise -- inexplicably wields his magical hammer. Together, they set out on a harrowing cosmic adventure to uncover the mystery of the God Butcher's vengeance."
        ),
        MovieDetail(26,
            "How to Train Your Dragon : The Hidden World",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/How%20to%20Train%20Your%20Dragon%20-%20The%20Hidden%20World.jpg",
            40000,
            "XXI, CGV",
            "Hiccup aims to unite the vikings and the dragons in order to bring peace on the island of Berk. However, he must stop the evil Grimmel and his devious plans to wipe out all dragons."
        ),
        MovieDetail(27,
            "Spiderman : Far From Home",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/Spiderman%20-%20Far%20From%20Home.jpg",
            40000,
            "XXI, CGV, Platinum Cineplex",
            "Peter Parker, the beloved superhero Spider-Man, faces four destructive elemental monsters while on holiday in Europe. Soon, he receives help from Mysterio, a fellow hero with mysterious origins."
        ),
        MovieDetail(28,
            "Aladdin",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/Aladdin.jpg",
            40000,
            "XXI, CGV",
            "Aladdin, a kind thief, woos Jasmine, the princess of Agrabah, with the help of Genie. When Jafar, the grand vizier, tries to usurp the king, Jasmine, Aladdin and Genie must stop him from succeeding."
        ),
        MovieDetail(29,
            "Train to Busan",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/Train%20to%20Busan.jpg",
            40000,
            "XXI, CGV, Platinum Cineplex",
            "Seok-woo and his daughter are on a train to Busan on the latter's birthday to see his wife. However, the journey turns into a nightmare when they are trapped amidst a zombie outbreak in South Korea."
        ),
        MovieDetail(30,
            "The Lion King",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/The%20Lion%20King.jpg",
            40000,
            "XXI, CGV",
            "Simba, a young lion prince, flees his kingdom after the murder of his father, Mufasa. Years later, a chance encounter with Nala, a lioness, causes him to return and take back what is rightfully his."
        ),
        MovieDetail(31,
            "Toy Story 4",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/Toy%20Story%204.jpg",
            40000,
            "XXI, CGV, Platinum Cineplex",
            "Woody attempts to make Forky, a toy, suffering from existential crisis, realise his importance in the life of Bonnie, their owner. However, things become difficult when Gabby Gabby enters their lives."
        ),
        MovieDetail(32,
            "Eternals",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/Eternals.jpg",
            40000,
            "XXI, CGV",
            "The Eternals, a race of immortal beings with superhuman powers who have secretly lived on Earth for thousands of years, reunite to battle the evil Deviants."
        ),
        MovieDetail(33,
            "Spiderman : Homecoming",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/Spiderman%20-%20Homecoming.jpg",
            40000,
            "XXI, CGV, Platinum Cineplex",
            "Peter Parker tries to stop the Vulture from selling weapons made with advanced Chitauri technology while trying to balance his life as an ordinary high school student."
        ),
        MovieDetail(34,
            "Frozen II",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/Frozen%20II.jpg",
            40000,
            "XXI, CGV",
            "Queen Elsa begins to hear a mysterious melodic voice calling to her. Unsettled, she answers it, thus awakening the elemental spirits and setting into motion a quest to restore an old injustice."
        ),
        MovieDetail(35,
            "Jumanji Welcome to the Jungle",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/Jumanji%20Welcome%20to%20the%20Jungle.jpg",
            40000,
            "XXI, CGV, Platinum Cineplex",
            "When four students play with a magical video game, they are drawn to the jungle world of Jumanji, where they are trapped as their avatars. To return to the real world, they must finish the game."
        ),
        MovieDetail(36,
            "The Raid 2 : Berandal",
            "https://raw.githubusercontent.com/mraihanfauzii/JetpackComposeMovieAppPhoto/main/Movie%20Poster/The%20Raid%202%20-%20Berandal.jpeg",
            40000,
            "XXI, CGV",
            "After surviving a bloody fight with powerful gangsters, rookie Jakarta cop Rama (Iko Uwais) thinks he can resume a normal life. However, his exploits during that fateful incident have attracted the attention of criminals even more deadly than the last. His family at risk, Rama has no choice but to go under cover. He gets himself thrown in prison, where he befriends the son of a prominent crime kingpin. Rama must lay his own life on the line to finally destroy the criminal empire."
        ),
    )
}